#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "F8FC69A60FDD4A20BB9FD7A1F194078698CBA3718BA60E67198BABF923F5733A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CritterpediaPlus;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace CritterpediaPlus {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 8 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal CritterpediaPlus.MainWindow frmMainWindow;
        
        #line default
        #line hidden
        
        
        #line 15 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl tabsetMain;
        
        #line default
        #line hidden
        
        
        #line 16 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem tabHome;
        
        #line default
        #line hidden
        
        
        #line 28 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblWelcome;
        
        #line default
        #line hidden
        
        
        #line 29 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSubWelcome;
        
        #line default
        #line hidden
        
        
        #line 30 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblRecent;
        
        #line default
        #line hidden
        
        
        #line 47 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgCritter1;
        
        #line default
        #line hidden
        
        
        #line 48 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter1Name;
        
        #line default
        #line hidden
        
        
        #line 49 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter1CaughtDate;
        
        #line default
        #line hidden
        
        
        #line 50 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter1CaughtBy;
        
        #line default
        #line hidden
        
        
        #line 52 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgCritter2;
        
        #line default
        #line hidden
        
        
        #line 53 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter2Name;
        
        #line default
        #line hidden
        
        
        #line 54 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter2CaughtDate;
        
        #line default
        #line hidden
        
        
        #line 55 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter2CaughtBy;
        
        #line default
        #line hidden
        
        
        #line 57 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgCritter3;
        
        #line default
        #line hidden
        
        
        #line 58 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter3Name;
        
        #line default
        #line hidden
        
        
        #line 59 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter3CaughtDate;
        
        #line default
        #line hidden
        
        
        #line 60 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCritter3CaughtBy;
        
        #line default
        #line hidden
        
        
        #line 64 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem tabMyCritterpedia;
        
        #line default
        #line hidden
        
        
        #line 71 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblMyCrittersHeader;
        
        #line default
        #line hidden
        
        
        #line 79 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datMyCritters;
        
        #line default
        #line hidden
        
        
        #line 92 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem tabMuseum;
        
        #line default
        #line hidden
        
        
        #line 93 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem tabOtherIslanders;
        
        #line default
        #line hidden
        
        
        #line 94 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem tabAllCritters;
        
        #line default
        #line hidden
        
        
        #line 101 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblAllCrittersHeader;
        
        #line default
        #line hidden
        
        
        #line 109 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datAllCritters;
        
        #line default
        #line hidden
        
        
        #line 120 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem tabLogIn;
        
        #line default
        #line hidden
        
        
        #line 133 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblHeader;
        
        #line default
        #line hidden
        
        
        #line 134 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblLoginName;
        
        #line default
        #line hidden
        
        
        #line 135 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtLoginName;
        
        #line default
        #line hidden
        
        
        #line 136 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPassword;
        
        #line default
        #line hidden
        
        
        #line 137 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox pwdPassword;
        
        #line default
        #line hidden
        
        
        #line 138 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnChangePassword;
        
        #line default
        #line hidden
        
        
        #line 139 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnLogin;
        
        #line default
        #line hidden
        
        
        #line 140 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgLogin;
        
        #line default
        #line hidden
        
        
        #line 146 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.StatusBarItem staMessage;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/CritterpediaPlus;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.frmMainWindow = ((CritterpediaPlus.MainWindow)(target));
            
            #line 9 "MainWindow.xaml"
            this.frmMainWindow.Loaded += new System.Windows.RoutedEventHandler(this.frmMainWindow_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.tabsetMain = ((System.Windows.Controls.TabControl)(target));
            return;
            case 3:
            this.tabHome = ((System.Windows.Controls.TabItem)(target));
            
            #line 16 "MainWindow.xaml"
            this.tabHome.GotFocus += new System.Windows.RoutedEventHandler(this.tabHome_GotFocus);
            
            #line default
            #line hidden
            return;
            case 4:
            this.lblWelcome = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblSubWelcome = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.lblRecent = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.imgCritter1 = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.lblCritter1Name = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.lblCritter1CaughtDate = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.lblCritter1CaughtBy = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.imgCritter2 = ((System.Windows.Controls.Image)(target));
            return;
            case 12:
            this.lblCritter2Name = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.lblCritter2CaughtDate = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.lblCritter2CaughtBy = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.imgCritter3 = ((System.Windows.Controls.Image)(target));
            return;
            case 16:
            this.lblCritter3Name = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.lblCritter3CaughtDate = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.lblCritter3CaughtBy = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.tabMyCritterpedia = ((System.Windows.Controls.TabItem)(target));
            
            #line 64 "MainWindow.xaml"
            this.tabMyCritterpedia.GotFocus += new System.Windows.RoutedEventHandler(this.tabMyCritterpedia_GotFocus);
            
            #line default
            #line hidden
            return;
            case 20:
            this.lblMyCrittersHeader = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.datMyCritters = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 22:
            this.tabMuseum = ((System.Windows.Controls.TabItem)(target));
            return;
            case 23:
            this.tabOtherIslanders = ((System.Windows.Controls.TabItem)(target));
            return;
            case 24:
            this.tabAllCritters = ((System.Windows.Controls.TabItem)(target));
            
            #line 94 "MainWindow.xaml"
            this.tabAllCritters.GotFocus += new System.Windows.RoutedEventHandler(this.tabAllCritters_GotFocus);
            
            #line default
            #line hidden
            return;
            case 25:
            this.lblAllCrittersHeader = ((System.Windows.Controls.Label)(target));
            return;
            case 26:
            this.datAllCritters = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 27:
            this.tabLogIn = ((System.Windows.Controls.TabItem)(target));
            
            #line 120 "MainWindow.xaml"
            this.tabLogIn.GotFocus += new System.Windows.RoutedEventHandler(this.tabLogIn_GotFocus);
            
            #line default
            #line hidden
            return;
            case 28:
            this.lblHeader = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.lblLoginName = ((System.Windows.Controls.Label)(target));
            return;
            case 30:
            this.txtLoginName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.lblPassword = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.pwdPassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 33:
            this.btnChangePassword = ((System.Windows.Controls.Button)(target));
            
            #line 138 "MainWindow.xaml"
            this.btnChangePassword.Click += new System.Windows.RoutedEventHandler(this.btnChangePassword_Click);
            
            #line default
            #line hidden
            return;
            case 34:
            this.btnLogin = ((System.Windows.Controls.Button)(target));
            
            #line 139 "MainWindow.xaml"
            this.btnLogin.Click += new System.Windows.RoutedEventHandler(this.btnLogin_Click);
            
            #line default
            #line hidden
            return;
            case 35:
            this.imgLogin = ((System.Windows.Controls.Image)(target));
            return;
            case 36:
            this.staMessage = ((System.Windows.Controls.Primitives.StatusBarItem)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

